name: CI

on:
  push:
    branches:
      - feature/parallel-workflow
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: Install
    runs-on: ubuntu-20.04
    steps:
      - name: ⬇️ ・Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '50'

      - name: ⎔・Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --cache-folder $(yarn cache dir)

      - name: Compress workspace artifact
        run: tar --create --use-compress-program='zstd -T0' --file=/tmp/workspace.tar.zst .

      - name: Upload workspace artifact
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: /tmp/workspace.tar.zst
          retention-days: 3

  lint:
    name: 🔬 ・Lint
    needs: install
    runs-on: ubuntu-20.04
    steps:
      - name: 📥 ・Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Extract workspace artifact
        run: tar --extract --use-compress-program='zstd -d' --file=workspace.tar.zst

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run linter
        run: yarn lint --quiet
  test:
    name: 🔎 ・Test
    needs: install
    runs-on: ubuntu-20.04
    steps:
      - name: 📥 ・Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Extract workspace artifact
        run: tar --extract --use-compress-program='zstd -d' --file=workspace.tar.zst

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run tests
        run: yarn test
  typecheck:
    name: ⬡・Typecheck
    needs: install
    runs-on: ubuntu-20.04
    steps:
      - name: 📥 ・Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Extract workspace artifact
        run: tar --extract --use-compress-program='zstd -d' --file=workspace.tar.zst

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run typescript check
        run: yarn typecheck
  build:
    name: ⚙️ ・Build
    needs: install
    runs-on: ubuntu-20.04
    steps:
      - name: 📥 Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Extract workspace artifact
        run: tar --extract --use-compress-program='zstd -d' --file=workspace.tar.zst

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build app
        run: yarn build
  # synpress:
  #   name: 👘 ・Synpress
  #   needs: install
  #   runs-on: ubuntu-20.04
  #   container: cypress/browsers:node12.13.0-chrome78-ff70
  #   env:
  #     NODE_ENV: false
  #   steps:
  #     - name: ⬇️ ・Checkout repo
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: '50'

  #     - name: ⎔ Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'
  #         check-latest: true
  #         cache: 'yarn'

  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile --cache-folder $(yarn cache dir)

  #     - name: Install cypress
  #       run: yarn add -D cypress@9.2.0 --cache-folder $(yarn cache dir) && yarn cypress install && yarn cypress verify

  #     - name: Run synpress tests
  #       run: yarn synpress:ct
  #       continue-on-error: true

  #     - name: Merge test results into one
  #       run: npm run report:merge

  #     - name: Generate HTML report
  #       run: yarn run report:generate

  #     - name: Save code coverage results
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: synpress-coverage-report
  #         path: public-report/*

  cypress:
    name: 🎡 ・Cypress (${{ matrix.containers }})
    needs: install
    runs-on: ubuntu-20.04
    container:
      image: swapr/cypress_browser_sudo:latest
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        containers:
          [LiquidityTests, MenuBarTests, RewardsPageTests, SwapBoxTests, TokenMenuTests, TransactionSettingsTests]
    steps:
      - name: 📥 ・Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Extract workspace artifact
        run: tar --extract --use-compress-program='zstd -d' --file=workspace.tar.zst

      - name: Verify Cypress
        run: yarn cypress install && yarn cypress verify

      - name: Run cypress tests
        run: yarn cypress:ci './node_modules/.bin/cypress run -r mochawesome -s tests/cypress/integration/smoke/${{ matrix.containers }}.ts'
        continue-on-error: true

      - name: Merge test results into one
        run: |
          yarn run report:merge
          mv index.json ${{ matrix.containers }}.json

      # - name: Generate HTML report
      #   run: yarn run report:generate

      - name: Save code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.containers }}
          path: ${{ matrix.containers }}.json
  merge-cypress:
    name: ⬡・Merge
    needs: cypress
    runs-on: ubuntu-20.04
    steps:
      - name: 📥 ・Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: LiquidityTests
          path: report
      - uses: actions/download-artifact@v3
        with:
          name: MenuBarTests
          path: ~/mochawesome-report
      - uses: actions/download-artifact@v3
        with:
          name: RewardsPageTests
          path: ~/mochawesome-report
      - uses: actions/download-artifact@v3
        with:
          name: SwapBoxTests
          path: ~/mochawesome-report
      - uses: actions/download-artifact@v3
        with:
          name: TokenMenuTests
          path: ~/mochawesome-report
      - uses: actions/download-artifact@v3
        with:
          name: TransactionSettingsTests
          path: ~/mochawesome-report

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Merge test results into one
        run: yarn run report:merge

      - name: Generate HTML report
        run: yarn run report:generate

      - name: Save code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: public-report/*

  cleanup:
    name: 🧹 Cleanup
    needs: [install, lint, test, typecheck, build, cypress, merge-cypress]
    runs-on: ubuntu-20.04
    if: ${{ success() }}
    steps:
      - name: Delete workspace artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            workspace
            LiquidityTests
            MenuBarTests
            RewardsPageTests
            SwapBoxTests
            TokenMenuTests
            TransactionSettingsTests
