name: CI

on:
  push:
    branches:
      - feature/parallel-workflow
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: Install
    runs-on: ubuntu-20.04
    steps:
      - name: ⬇️ ・Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '50'

      - name: ⎔・Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --cache-folder $(yarn cache dir)

      - name: Compress workspace artifact
        run: tar --create --use-compress-program='zstd -T0' --file=/tmp/workspace.tar.zst .

      - name: Upload workspace artifact
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: /tmp/workspace.tar.zst
          retention-days: 3

  lint:
    name: 🔬 ・Lint
    needs: install
    runs-on: ubuntu-20.04
    steps:
      - name: 📥 ・Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Extract workspace artifact
        run: tar --extract --use-compress-program='zstd -d' --file=workspace.tar.zst

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run linter
        run: yarn lint --quiet
  test:
    name: 🔎 ・Test
    needs: install
    runs-on: ubuntu-20.04
    steps:
      - name: 📥 ・Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Extract workspace artifact
        run: tar --extract --use-compress-program='zstd -d' --file=workspace.tar.zst

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run tests
        run: yarn test
  typecheck:
    name: ⬡・Typecheck
    needs: install
    runs-on: ubuntu-20.04
    steps:
      - name: 📥 ・Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Extract workspace artifact
        run: tar --extract --use-compress-program='zstd -d' --file=workspace.tar.zst

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run typescript check
        run: yarn typecheck
  build:
    name: ⚙️ ・Build
    needs: install
    runs-on: ubuntu-20.04
    steps:
      - name: 📥 Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Extract workspace artifact
        run: tar --extract --use-compress-program='zstd -d' --file=workspace.tar.zst

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build app
        run: yarn build
  synpress:
    name: 👘 ・Synpress
    needs: install
    runs-on: ubuntu-20.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
    env:
      NODE_ENV: false
    steps:
      - name: ⬇️ ・Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '50'

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --cache-folder $(yarn cache dir)

      - name: Install cypress
        run: yarn add -D cypress@9.2.0 --cache-folder $(yarn cache dir) && yarn cypress install && yarn cypress verify

      - name: Run synpress tests
        run: yarn synpress:ct

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        if: ${{ github.event.pull_request.title != '' }}
        run: npm run report:generate -t "${{ github.event.pull_request.title }}"

      - name: Generate HTML report
        if: ${{ github.event.pull_request.title == '' }}
        run: npm run report:generate -t "Commit"

      - name: Save code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: synpress-coverage-report
          path: public-report/*

  cypress:
    name: 🎡 ・Cypress
    needs: install
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node12.18.3-chrome87-ff82
      options: --user 1001
    steps:
      - name: ⬇️  Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '50'

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --cache-folder $(yarn cache dir)

      - name: Install cypress
        run: yarn add -D cypress@9.2.0 --cache-folder $(yarn cache dir) && yarn cypress install && yarn cypress verify

      - name: Run cypress tests
        run: yarn cypress:ct

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        if: ${{ github.event.pull_request.title != '' }}
        run: npm run report:generate -t "${{ github.event.pull_request.title }}"

      - name: Generate HTML report
        if: ${{ github.event.pull_request.title == '' }}
        run: npm run report:generate -t "Commit"

      - name: Save code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-coverage-report
          path: public-report/*

  cleanup:
    name: 🧹 Cleanup
    needs: [install, lint, test, typecheck, build]
    runs-on: ubuntu-20.04
    if: ${{ success() }}
    steps:
      - name: Delete workspace artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: workspace
