name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CI:
    name: Build
    runs-on: ubuntu-20.04
    # Cypress Docker image with Chrome v78
    # and Firefox v70 pre-installed
    container: cypress/browsers:node12.13.0-chrome78-ff70
    env:
      NODE_ENV: false
    strategy:
      matrix:
        node_version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: cyrpress bin
        run: npx cypress install
      - name: cyrpress bin2
        run: cypress install
      - name: test
        run: yarn synpress:ct
      - name: Build
        run: yarn run build
