name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CI:
    name: Build
    runs-on: ubuntu-20.04
    # Cypress Docker image with Chrome v78
    # and Firefox v70 pre-installed
    container: cypress/browsers:node12.13.0-chrome78-ff70
    strategy:
      matrix:
        node_version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: yarn install
        env:
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/.cache/Cypress
      - name: Cache NPM and Cypress 📦
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Lint
        run: yarn lint
      - name: test
        run: yarn synpress:ct
        env:
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/.cache/Cypress
      - name: Build
        run: yarn run build
